### ISSUE TITLE
Inject your dependencies dependencies

### ISSUE THREAD

**Issue by eranimo** [taptapship/wiredep#160]
Say that you include angular-bootstrap, and it requires bootstrap. How can you configure wiredep to inject bootstrap as well? Basically I want to wire everything in the bower folder, not just your own dependencies.

**Comment by stephenplusplus** [comment]
wiredep will inject a dependency's dependencies. In the case of angular-bootstrap, it only lists [angular as a dependency](https://github.com/angular-ui/bootstrap-bower/blob/master/bower.json#L17), so you will get:

```html
<!-- bower:js -->
<script src="bower_components/angular/angular.js"></script>
<script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
<!-- endbower -->
```

**Comment by eranimo** [comment]
I don't know what else do say besides it doesn't seem to be doing that. I have a dependency that requires angular-slugify that is clearly listed in the bower.json file of that dependency. The project that requires this dependency does not list angular-slugify. The command line method also does not list angular-slugify. Could it be a problem with that particular project?

**Comment by stephenplusplus** [comment]
Can you whip up some type of hierarchical bower.json representation of your project so I can understand better?

**Comment by mkoryak** [comment]
I was looking into this issue and narrowed it down to the following code:
```js 
if (dep.main.length === 0 && !depIsExcluded) {
      // can't find the main file. this config file is useless!
      config.get('on-main-not-found')(component);
      return;
    }
```

The dependencies who's dependencies where not getting injected did not have a main file. I can see how this might be the desired behavior, but in our case we use bower to pull down source code of some internal components and then build them all with the main project. We need their dependancies to be present, but the components do not specify a main file.

It might be nice to have an option to include things that dont have a main file instead of having to add a bogus main to those bower.json of those repos

Thanks
