### ISSUE TITLE
Visual Studio File Path in Windows won't allow for Bower Injection

### ISSUE THREAD

**Issue by xtianus79** [taptapship/wiredep#171]
After a couple days it has been discovered that VS 2015 CTP 6 and previously I imagine won't allow a folder that is inside of the project folder to utilized teh wiredep bower injection.  

Through deduction it has been discovered that the root cause is the folder name "Visual Studio 2015" having spaces prevents wiredep from working.  

Adding @madskristensen @sayedihashimi

**Comment by sayedihashimi** [comment]
@xtianus79 it sounds like a wiredep bug unless I've misunderstood your issue.

**Comment by xtianus79** [comment]
it is most likely a wiredep issue and that is why I posted it here.  However, with that being said... and I am new to Visual Studio... The folder location of projects being in my documents folder with a name of spaces is proving to be a nightmare on many fronts.  I can't get my nuget package manager working anymore.  But i digress.

**Comment by stephenplusplus** [comment]
Can you provide your bower.json, wiredep configuration, actual results, and expected results?

**Comment by xtianus79** [comment]
bower.json "dependencies": {
    "foundation": "zurb/bower-foundation"<% if (fontAwesome) { %>,
    "font-awesome": "~4.3.0" <% } %>
  }
}

package.json "devDependencies": {
    "load-grunt-tasks": "~3.1.0",<% if (!compass) { %>
    "node-sass": "~2.0.1",
    "grunt-sass": "~0.18.0",<% } else { %>
    "grunt-contrib-sass": "~0.9.2",<% } %>
    "grunt": "~0.4.5",<% if (jade) { %>
    "grunt-contrib-jade": "~0.14.1",<% } %>
    "grunt-contrib-watch": "~0.6.1",
    "grunt-contrib-clean": "~0.6.0",
    "grunt-contrib-copy": "~0.8.0",
    "grunt-contrib-cssmin": "~0.12.2",
    "grunt-contrib-uglify": "~0.8.0",
    "grunt-contrib-concat": "~0.5.1",
    "grunt-contrib-jshint": "~0.11.0",
    "grunt-contrib-connect": "~0.9.0",
    "grunt-wiredep": "~2.0.0",
    "grunt-usemin": "~3.0.0",
    "grunt-contrib-imagemin": "0.9.3",
    "grunt-newer": "~1.1.0"
  }
}


		wiredep: {
			target: {
				src: [<% if (jade) { %>
					'<%%= app %>/**/*.jade'<% } else { %>
					'<%%= app %>/**/*.html'<% } %>
				],
				exclude: [
					'modernizr',<% if (fontAwesome) { %>
					'font-awesome',<% } %>
					'jquery-placeholder',
					'foundation'
				]
			}
		}

	});

wiredep configuration
	<% if (jade) { %>grunt.registerTask('compile-jade', ['jade']);<% } %>
	grunt.registerTask('compile-sass', ['sass']);
	grunt.registerTask('bower-install', ['wiredep']);
	<% if (jade) { %>
	grunt.registerTask('default', ['compile-jade', 'compile-sass', 'bower-install', 'connect:app', 'watch']);<% } else { %>
	grunt.registerTask('default', ['compile-sass', 'bower-install', 'connect:app', 'watch']);<% } %>
	grunt.registerTask('validate-js', ['jshint']);
	grunt.registerTask('server-dist', ['connect:dist']);
	<% if (jade) { %>
	grunt.registerTask('publish', ['compile-jade', 'compile-sass', 'clean:dist', 'validate-js', 'useminPrepare', 'copy:dist', 'newer:imagemin', 'concat', 'cssmin', 'uglify', 'usemin']);<% } else { %>
	grunt.registerTask('publish', ['compile-sass', 'clean:dist', 'validate-js', 'useminPrepare', 'copy:dist', 'newer:imagemin', 'concat', 'cssmin', 'uglify', 'usemin']);<% } %>


So anywhere I install and use this framework everything works fine.  However, when i place a folder anywhere inside of a VS project folder the result is wiredep will not work.  It is the oddest thing but the one thing I did to correct the issue was created a project not in the VS default folder setup which is Visual Studio 2015 but rather something that is VS2015 and it works fine.  

@sayedihashimi I can't say for sure it is wiredep but through deduction this is all I can come up with.  However, now that my folder structure has changed for VS my nuget package manager won't work...

**Comment by xtianus79** [comment]
@sayedihashimi I spent literally all weekend trying to deal with the StarterWeb Template.  I have no clue where the folder directives are coming from and why certain things are expluded and certain things are not.  There has to be a JS conflict.

**Comment by jhubsharp** [comment]
Just to add in, this doesn't seem to be an issue with Visual Studio. I'm using 2015 Community RC and my bower injection works fine. I am not using the Documents path though, and the path I am using has no spaces.

**Comment by sayedihashimi** [comment]
@xtianus79 
>@sayedihashimi I spent literally all weekend trying to deal with the StarterWeb Template. 

I'm sorry to hear that. You may have received some help here that would have helped previously but haven't yet. I suspect that is because this bug report, along with further comments, is authored very poorly. I still have no idea on the following.

 1. How to reproduce the problem
 1. What is the error message or invalid results

When submitting a bug you're primary goals should be; to communicate what the problems are and steps for someone to reproduce the issue.

You've given some information here and even some sample code, but you never stated steps to reproduce the issue, and you never gave expected and actual results.

Previously in the thread

@stephenplusplus asked
>Can you provide your bower.json, wiredep configuration, actual results, and expected results?

You provided the content of the files but not expected and actual results.

In this particular case I'd recommend that you create a .zip file of a project which reproduces the issue and then provide steps to reproduce. For example.

 1. Download my sample from _url here_
 2. Extract files to a folder that has a space in it, in my case I used ```C:\Users\Sayed\Documents\Visual Studio 2015\Projects\EmptyWeb```
 3. Then ...

If the appropriate people cannot reproduce the issue or understand what's happening in your case then it will be difficult for anyone to help you.

In the current state this issue is not very actionable and requires guessing on the part of maintainers to try and help you which is not a good use of anyone's time.

I've seen other issues that you've filed and they suffer from the same problems. I'd recommend that you spend some time investigating how you can improve your future bug reports. I searched for a good article but didn't find one that stood out. I did find the following links which you may find helpful though.

 - [How to write a quality bug report](http://university.utest.com/writing-quality-bug-reports-and-utest-etiquette/)
 - [How to Report Bugs Effectively](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html)
 - [Writing Better Bug Reports](http://martiancraft.com/blog/2014/07/good-bug-reports/)

**Comment by xtianus79** [comment]
I have long since figured this out.... It was a wiredep issue I believe. I have since worked this out in my generators build.  thanks for the help.
