### ISSUE TITLE
ignoredDependencies in .bowerrc file leads to an error

### ISSUE THREAD

**Issue by bbuhler** [taptapship/wiredep#233]
I have created an **.bowerrc** file like described [here](http://stackoverflow.com/a/27791606/4512842).

```
{
  "ignoredDependencies": [
    "bootstrap-sass",
    "jquery"
  ]
}
```

When I run wiredep it raises the following error:
```
Error: Error: bootstrap-sass is not installed. Try running `bower install` or remove the component from your bower.json file.
```

Even when I configure the ignored components to be excluded in wiredep.

**Comment by eddiemonge** [comment]
Where did you get `ignoredDependencies ` from? Use `exclude ` https://github.com/taptapship/wiredep#configuration

**Comment by bbuhler** [comment]
@eddiemonge the `ignoredDependencies` property are in my **.bowerrc** configuration file.
(See http://bower.io/docs/config/#bowerrc-specification)

As I already mentioned I tried to use the `exclude` property of wiredep configuration.

Using `exclude` does not solve the error. Please re-open this issue.

**Comment by eddiemonge** [comment]
What is your configuration? How are you using exclude?

**Comment by bbuhler** [comment]
I created a [test repo](https://github.com/bbuhler/wiredep-bowerrc-ignore-dep) where you can reproduce the error as follows:
- checkout repo
- npm install
- npm start

**Comment by eddiemonge** [comment]
Interesting. So the problem is that one of your dependencies require an excluded dependency. Because of that, wiredep is trying to go into that second dependency to determine what its dependencies are. So even though the parent is being excluded, it will still try to include its children. I'm not sure if this is an actual bug or an awesome feature.

**Comment by eddiemonge** [comment]
So the short answer is to install them using bower then they wont get added because of the exclude.

**Comment by moravcik** [comment]
I have the same problem. I think wiredep should accept Bower's standard way of ignoring dependencies (via `ignoredDependencies` in .bowerrc) or at least do not raise errors for missing dependencies which are stated to exclude.
Installing dependencies with bower and using only exclude as it was suggested is not perfect in my case, since I use other gulp tasks to scan all bower_components and so I need to exclude the same dependencies in multiple places, which I think is not the best practice.

**Comment by yumyo** [comment]
Ignoring dependencies via bower overrides fix the issue for me.

Eg. to wiredep fullpage.js without jquery.
```
"fullpage.js": {
    "main": [
        "./dist/jquery.fullpage.min.js"
    ],
    "dependencies": {}
},
```

**Comment by shishirsharma** [comment]
https://github.com/taptapship/wiredep/issues/233#issuecomment-198026349 Solves my problem.
