### ISSUE TITLE
Add an option to take minified (or not) javascript file.

### ISSUE THREAD

**Issue by kvpt** [taptapship/wiredep#52]
Hello,

Most libraries have two versions XXX.js and XXX.min.js.
Ideally standard version should be taked in dev build task and minified version in production build task.
For now, min and standard versions of the differents library are mixed, because of the main directive in bower file rarely present and it's impossible to change this behavior.
So it would be fine to add an option for this.
Moreover this would save time on minification task.

Thanks.

**Comment by ClimbsRocks** [comment]
@stephenplusplus : (this is asked out of ignorance, not judgment): 

I'd actually heard that it was considered a best practice for package authors TO include a minified version, since minifying software can wreak unintentional havoc occasionally. I'd heard that the package authors including an official minified version means they can insure the minification worked most optimally for their specific package. 

Could you explain why it's becoming a best practice for packages to not include a minified version, and whether this applies to large/complex packages like jQuery?

**Comment by nickcmaynard** [comment]
I'd really like this, too.  

I'm building a number of applications with libraries like Ionic, AngularJS (and its plugins).  All of these libraries include .min.js and .min.css versions with them.

By not including this functionality, developers are *forced* to write minification procedures.  This is not necessarily something that everyone should have to do, particularly if the Bower package authors have included minified versions.

I certainly would like to see a tunable here that detects if a (named according to a standard pattern) min.js/min.css equivalent exists for a given JS/CSS file, and injects that instead.

**Comment by CarbonFactory** [comment]
+1 for this feature request

**Comment by CWSpear** [comment]
The [`bower.json` spec](https://github.com/bower/bower.json-spec#main) says:

> Do not include minified files

**Comment by nickcmaynard** [comment]
@CWSpear - this request isn't about handling minified files defined in `main`.  Rather, it's about *detecting* minified *equivalents* of files defined in `main`, but provided by the package authors, and providing a tunable to use those instead.

**Comment by CarbonFactory** [comment]
I've made this [Gist](https://gist.github.com/CarbonFactory/851d285269e379fb6529) which is very hacky in nature but does the job. 

Using overrides is too much manual work and minifying ourselves may lead to bugs.

**Comment by CWSpear** [comment]
If "minifying ourselves" is leading to bugs, that's likely a bug in the author's code. They shouldn't write such fragile code!

**Comment by CarbonFactory** [comment]
If we are using around 30-40 libraries and all of them have minified versions, it makes sense in using them, instead of taking the un-minified files and again minifying them. And, most of these are big libraries and have huge lines of code and it "may" fail due to the way we are minifying it or due to the tools we use to do it.

**Comment by nickcmaynard** [comment]
@stephenplusplus Given the ongoing conversation, could we reopen this issue, please?

**Comment by sabrehagen** [comment]
This seems like a logical addition. Self minification of packages is plaguing me and it would be better if I  could use the author approved version.

**Comment by vincent-zurczak** [comment]
I agree, such an option would be very useful.

**Comment by donovanmuller** [comment]
+1

**Comment by stephenplusplus** [comment]
We have to stick with the Bower spec on this issue. Bower advises not to include minified files and it recently restricted `main` to be an array defining only one file of each type.

**Comment by AndrwM** [comment]
+1

**Comment by SolomoN-ua** [comment]
+1

**Comment by zfoltin** [comment]
+1

**Comment by elabeca** [comment]
+1

**Comment by karvapallo** [comment]
+1

**Comment by Samurais** [comment]
+1

**Comment by Sheparzo** [comment]
+1
